### ISSUE TITLE
Profile Info

### ISSUE THREAD

**Issue by swr5da** [bwang22/logoff#15]
For Neighbor profiles ask for:
-Name (required)
-Individual or family (required)
-Email (required)
-Affiliate church, fellowship, or organization (optional)
-Zip Code (required)
-Select the issues they care about (required options to check):
- sex trafficking and labor slavery 
- homelessness
- tutoring and mentoring
- Food Justice  and creation care
- Criminal Justice
- Clean Water 
- Veterans
- Elderly, sick and shut-in 
- How would you like to love your neighbors?(required)
- Three option (required): time (hours you can volunteer), talents (skills to help others), treasures (looking to give $$$). 

(((LATER)))Time shows how much time a week you could usually dedicate to service. Talent shows a list of skills to choose from. Treasures is about financial giving as well as spare items you may have.

**Comment by swr5da** [comment]
People should choose between being an individual/family or an organization.
If they are an individual/family they will fill out the Neighbor profile (above).

If they are an Organization ask for:
-Name
-Email
-Phone number
-Affiliate church, fellowship, or organizations
-SPECIFIC ADDRESS
-NEEDS YOU HAVE
-LOCATIONS YOU SERVE
-SERVICES YOU PROVIDE

**Comment by bwang22** [comment]
FOR PARTNERS not INDIVIDUALS:

-Name (required)
-Individual or family (required)
-Email (required)
-Affiliate church, fellowship, or organization (optional)
-Zip Code (required)
-Select the issues they care about (required options to check):

sex trafficking and labor slavery
homelessness
tutoring and mentoring
Food Justice and creation care
Criminal Justice
Clean Water
Veterans
Elderly, sick and shut-in

How would you like to love your neighbors?(required)

Three option (required): time (hours you can volunteer), talents (skills to help others), treasures (looking to give $$$).

**Comment by bwang22** [comment]
Single pass for databased linked to current profile. Can only be used once signed in. This is for mapping partners

**Comment by bwang22** [comment]
done
