### ISSUE TITLE
Geolocation Function and Current Location and Pulling Closest Places

### ISSUE THREAD

**Issue by swr5da** [bwang22/logoff#19]
Can we get an actual location from the longitude and latitude? 
Convert longitude and latitude to actual location

Share location by "Laying Hands" for prayer requests

Option for sharing location via clicking on the "Laying Hands" icon.  Cater to privacy preferences 

Change from pulling all places in x radius to pull closest 5 for each category

**Comment by bwang22** [comment]
completed
