### ISSUE TITLE
Prayer Requests - Pray for people praying 

### ISSUE THREAD

**Issue by swr5da** [bwang22/logoff#22]
A neighbor or a partner puts a prayer out and everyone is notified. 
Add icon in feed for prayer request you could "lay hands" (pray for), have option to like and to share it. 
Share other peoples prayer request. 

Get updates of what your friends are praying for 
"So and so is praying about this"
Notifications about people praying for a specific thing correlated to bouncing pin.

**Comment by bwang22** [comment]
Now explosion
